-- Code generated by sprotodump
-- DO NOT EDIT!
return {
  protocol = {},
  type = {
    AddressBook = {
      {
        array = true,
        key = "id",
        map_keyfield = {
          meta = "\27[1;31m at test.sproto:3 line\27[0m",
          name = "id",
          tag = 1,
          typename = "integer"
        },
        map_valuefield = {
          array = true,
          key = "id",
          map_keyfield = {
            meta = "\27[1;31m at test.sproto:3 line\27[0m",
            name = "id",
            tag = 1,
            typename = "integer"
          },
          meta = "\27[1;31m at test.sproto:18 line\27[0m",
          name = "person",
          tag = 0,
          typename = "Person"
        },
        meta = "\27[1;31m at test.sproto:18 line\27[0m",
        name = "person",
        tag = 0,
        typename = "Person"
      },
      meta = "\27[1;31m at test.sproto:17 line\27[0m"
    },
    Person = {
      {
        meta = "\27[1;31m at test.sproto:2 line\27[0m",
        name = "name",
        tag = 0,
        typename = "string"
      },
      {
        meta = "\27[1;31m at test.sproto:3 line\27[0m",
        name = "id",
        tag = 1,
        typename = "integer"
      },
      {
        array = true,
        meta = "\27[1;31m at test.sproto:11 line\27[0m",
        name = "phone",
        tag = 4,
        typename = "Person.PhoneNumber"
      },
      {
        array = true,
        key = "",
        map = true,
        map_keyfield = {
          meta = "\27[1;31m at test.sproto:7 line\27[0m",
          name = "number",
          tag = 99,
          typename = "string"
        },
        map_valuefield = {
          meta = "\27[1;31m at test.sproto:8 line\27[0m",
          name = "type",
          tag = 1000,
          typename = "integer"
        },
        meta = "\27[1;31m at test.sproto:12 line\27[0m",
        name = "phonemap",
        tag = 5,
        typename = "Person.PhoneNumber"
      },
      {
        array = true,
        key = "number",
        map_keyfield = {
          meta = "\27[1;31m at test.sproto:7 line\27[0m",
          name = "number",
          tag = 99,
          typename = "string"
        },
        map_valuefield = {
          array = true,
          key = "number",
          map_keyfield = {
            meta = "\27[1;31m at test.sproto:7 line\27[0m",
            name = "number",
            tag = 99,
            typename = "string"
          },
          meta = "\27[1;31m at test.sproto:13 line\27[0m",
          name = "phonemapkv",
          tag = 6,
          typename = "Person.PhoneNumber"
        },
        meta = "\27[1;31m at test.sproto:13 line\27[0m",
        name = "phonemapkv",
        tag = 6,
        typename = "Person.PhoneNumber"
      },
      {
        meta = "\27[1;31m at test.sproto:14 line\27[0m",
        name = "onephone",
        tag = 7,
        typename = "Person.PhoneNumber"
      },
      meta = "\27[1;31m at test.sproto:1 line\27[0m"
    },
    ["Person.PhoneNumber"] = {
      {
        meta = "\27[1;31m at test.sproto:7 line\27[0m",
        name = "number",
        tag = 99,
        typename = "string"
      },
      {
        meta = "\27[1;31m at test.sproto:8 line\27[0m",
        name = "type",
        tag = 1000,
        typename = "integer"
      },
      meta = "\27[1;31m at test.sproto:6 line\27[0m"
    }
  }
}